PeopleManager.Ui.Mvc/Models/ErrorViewModel.cs
namespace PeopleManager.Ui.Mvc.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PeopleManager.Ui.Mvc/Models/Person.cs
using System.ComponentModel.DataAnnotations;

namespace PeopleManager.Ui.Mvc.Models
{
    public class Person
    {
        public int Id { get; set; }

        [Display(Name ="First Name")]//Dit doet niks met de code, dit is meer voor het renderen van het formulier makkelijker te maken.
        [Required]
        public required string FirstName { get; set; }

        [Display(Name = "Last Name")]
        [Required]
        public required string LastName { get; set; }

        [Display(Name = "Email")]
        [EmailAddress]
        [Required]//required: voor userinterface
        public required string Email { get; set; }//required voor programmeur in code

        [Display(Name = "Description")]
        public string? Description { get; set; }
    }
}

PeopleManager.Ui.Mvc/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using PeopleManager.Ui.Mvc.Core;
using PeopleManager.Ui.Mvc.Models;
using System.Diagnostics;

namespace PeopleManager.Ui.Mvc.Controllers
{   
    public class HomeController : Controller
    {
        private readonly PeopleManagerdbContext _DbContext;
      public HomeController(PeopleManagerdbContext DbContext)
        {
            _DbContext = DbContext;
        }
        public IActionResult Index()
        {
            var people = _DbContext.People.ToList();
            return View(people);
        }

        public IActionResult Privacy()
        {
            return View();
        }
        
        [HttpGet("Home/Detail/{id:int}")]
        public IActionResult Detail(int id)           
        {
            var people = GetPeople();
            var person = people.FirstOrDefault(p => p.Id == id);

            if(person is null)
            {
                return RedirectToAction("Index");
            }
            //Roept view PErsonDetail op ook al is de action naam niet hetzelfde door het in de return view te zetten vindt hij en nu wel.
            return View("PersonDetail", person);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        private IList<Person> GetPeople()
        {
            return new List<Person>
            {
                new Person{Id= 1, FirstName = "Kacper", LastName = "Juras", Email = "kacper.juras@student.vives.be" },
                new Person{Id= 2, FirstName = "Qendrim", LastName = "Selmani", Email = "qendrim.selmani@student.vives.be" },
                new Person{Id= 3, FirstName = "Jona", LastName = "Depressed", Email = "jona.depressed@student.vives.be" },
                new Person{Id= 4, FirstName = "Aaron", LastName = "Carreyn", Email = "aaron.carreyn@student.vives.be"}
            };
        }
    }
}

PeopleManager.Ui.Mvc/Controllers/PeopleController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PeopleManager.Ui.Mvc.Core;
using PeopleManager.Ui.Mvc.Models;

namespace PeopleManager.Ui.Mvc.Controllers
{
    public class PeopleController : Controller
    {
        private readonly PeopleManagerdbContext _database;
        public PeopleController(PeopleManagerdbContext database)
        {
            _database = database;
        }
        public IActionResult Index()
        {
            var people = _database.People.ToList();
            return View(people);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Person person)
        {
            _database.People.Add(person);
            _database.SaveChanges(); 
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var person = _database.People.Find(id);
            {
                if (person == null) 
                {
                    return RedirectToAction("Index");
                }
            }
            return View(person);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit([FromRoute]int id, Person person)
        {
            var dbPerson = _database.People.Find(id);
            {
                if(dbPerson == null)
                {
                    return RedirectToAction("Index");
                }
            }
            dbPerson.FirstName =person.FirstName;
            dbPerson.LastName =person.LastName;
            dbPerson.Email =person.Email;
            dbPerson.Description =person.Description;


            _database.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

PeopleManager.Ui.Mvc/Views/Home/Index.cshtml
@model IList<Person>

@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome Summoner</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

<div class="row">
    @foreach (var person in Model)
    {
        <div class="col-4">
            <partial name="PersonCardPartial" model="person"/>
        </div>
    }
</div>

PeopleManager.Ui.Mvc/Views/Home/PersonCardPartial.cshtml
@model Person

<div class="card">
    <div class="card-header">
        <a asp-action="Detail" asp-route-id="@Model.Id">
        <h2>@Model.FirstName @Model.LastName</h2>
        </a>
    </div>

    <div class="card-body">
        <a class="btn btn-outline-primary" href="mailto:@Model.Email">Contact</a>
    </div>
</div>

PeopleManager.Ui.Mvc/Views/Home/PersonDetail.cshtml
@model Person

<div class="row">
	<div class="="col-4><strong>First Name:</strong></div>
	<div class="="col-8>@Model.FirstName</div>
</div>

<div class="row">
	<div class="=" col-4><strong>Last Name:</strong></div>
	<div class="=" col-8>@Model.LastName</div>
</div>

<div class="row">
	<div class="=" col-4><strong>Email:</strong></div>
	<div class="=" col-8>@Model.Email</div>
</div>

<div class="row">
	<div class="=" col-4><strong>Description:</strong></div>
	<div class="=" col-8>@Model.Description</div>
</div>

PeopleManager.Ui.Mvc/Views/People/Index.cshtml
@model IList<Person>

@{
    ViewData["Title"] = "People Index";
}

<h1>People Index</h1>
<a asp-action="Create" class="btn btn-primary">Create New Person</a>

<table class="table table-striped">
    <thead>
        <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var person in Model)
        {
            <partial name="PersonRowPartial" model="person"/>
        }
    </tbody>
</table>

PeopleManager.Ui.Mvc/Views/People/PersonRowPartial.cshtml
@model Person

<tr>
    <td>@Model.FirstName</td>
    <td>@Model.LastName</td>
    <td>
        <a href="mailto:@Model.Email">
            @Model.Email
        </a>
    </td>
    <td>
        <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-primary">Edit</a>
    </td>
</tr>

PeopleManager.Ui.Mvc/Views/People/create.cshtml
@model Person

@{
	ViewBag.Title = "Create Person";
}
<h1>@ViewBag.Title</h1>

<form method="post">
    <div class="mb-3">
        <label asp-for="FirstName" class="form-label"></label>
        <input asp-for="FirstName" class="form-control" />        
    </div>

    <div class="mb-3">
        <label asp-for="LastName" class="form-label">Last Name</label>
        <input asp-for="LastName" class="form-control" />
    </div>

    <div class="mb-3">
        <label asp-for="Email" class="form-label"></label>
        <input asp-for="Email" class="form-control" />
    </div>

    <div class="mb-3">
        <label asp-for="Description" class="form-label"></label>
        <textarea asp-for="Description" class="form-control"></textarea>
    </div>
    
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

PeopleManager.Ui.Mvc/Views/People/edit.cshtml
@model Person

@{
	ViewBag.Title = "Edit Person";
}
<h1>@ViewBag.Title</h1>

<form method="post">
    <div class="mb-3">
        <label asp-for="FirstName" class="form-label"></label>
        <input asp-for="FirstName" class="form-control" />        
    </div>

    <div class="mb-3">
        <label asp-for="LastName" class="form-label">Last Name</label>
        <input asp-for="LastName" class="form-control" />
    </div>

    <div class="mb-3">
        <label asp-for="Email" class="form-label"></label>
        <input asp-for="Email" class="form-control" />
    </div>

    <div class="mb-3">
        <label asp-for="Description" class="form-label"></label>
        <textarea asp-for="Description" class="form-control"></textarea>
    </div>
    
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

PeopleManager.Ui.Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PeopleManager.Ui.Mvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PeopleManager.Ui.Mvc.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PeopleManager.Ui.Mvc</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="People" asp-action="Index">People</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - PeopleManager.Ui.Mvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>